### ISSUE TITLE
scry server crashes if vscode is launched from Spotlight on macOS, but not if launched from shell

### ISSUE THREAD

**Issue by doughsay** [faustinoaq/vscode-crystal-lang#14]
This happens when scry attempts to create and write to `.scry.out`.  If vscode is launched from Spotlight or Finder on macOS, the "PWD" is apparently set to `/`, so scry tries creating and writing to `/.scry.out`:

![image](https://user-images.githubusercontent.com/221693/29104235-1fcd4198-7c79-11e7-8fb7-fc3f4bc7af58.png)

If I launch vscode from my shell (i.e. `code .`), it inherits the PWD correctly and scry writes to `./.scry.out`.

**Comment by faustinoaq** [comment]
Fixed by https://github.com/kofno/scry/pull/18
