### ISSUE TITLE
while requiring "prelude": can't find file 'prelude'

### ISSUE THREAD

**Issue by faustinoaq** [faustinoaq/vscode-crystal-lang#15]
Crystal can't find stdlib.

Seems to be a CRYSTAL_PATH issue

This line is the problem https://github.com/faustinoaq/vscode-crystal-lang/blob/master/src/crystalConfiguration.ts#L18

MacOS output for `crystal env` by @doughsay

```
CRYSTAL_CACHE_DIR="/Users/chris/.cache/crystal"
CRYSTAL_PATH="/usr/local/Cellar/crystal-lang/0.23.1/src:lib"
CRYSTAL_VERSION="0.23.1"
```

Proposal by @watzon:

> make that line contingent upon the OS

**Comment by doughsay** [comment]
It works now, thanks!

**Comment by watzon** [comment]
Thanks for the mention @faustinoaq . Always good to feel like I've contributed
