### ISSUE TITLE
Support for darwin

### ISSUE THREAD

**Issue by faustinoaq** [faustinoaq/vscode-crystal-lang#3]
@akzhan I added your binary, but I don't know if my [crystalMain.ts](https://github.com/faustinoaq/vscode-crystal-lang/blob/master/src/crystalMain.ts) is well configured to support this.

Can you confirm me that this extension work with the darwin binary?

The branch is https://github.com/faustinoaq/vscode-crystal-lang/tree/darwin-scry-support

BTW, thanks you!

**Comment by akzhan** [comment]
I didnt install extensions by hands :) will do but later (2-24h).

**Comment by faustinoaq** [comment]
@akzhan thanks you!

Please before do this:
`git pull` and recompile Scry, I added some fixes to formatting support in the tast commit, see https://github.com/faustinoaq/scry/commit/49012845ae63e74ec682bf698ff9170547aeaa24

**Comment by akzhan** [comment]
Sorry for delay, just learned about extensions. Update package version to something high to turn off autoupdate and run extension.

Got

```
Error: No such module: icu
    at importPunycode (url.js:5:20)
    at url.js:11:21
    at url.js:960:3
    at NativeModule.compile (bootstrap_node.js:528:7)
    at NativeModule.require (bootstrap_node.js:468:18)
    at _http_client.js:5:13
    at _http_client.js:673:3
    at NativeModule.compile (bootstrap_node.js:528:7)
    at NativeModule.require (bootstrap_node.js:468:18
```

**Comment by faustinoaq** [comment]
@akzhan that error is strange, I never seen `Error: No such module: icu` before.

Seems to be related to VSCode insiders version, see: https://github.com/Microsoft/vscode/issues/23639

Are you using VSCode Insider?

If yes, try to install VSCode latest stable version `1.13.0`

**Comment by faustinoaq** [comment]
Hi !

Now Scry server isn't distributed with this extension.

README message:

> Scry server isn't distributed with this extension. You need to compile it from scry-vscode-crystal-lang and configure on settings.json

Please, see https://github.com/faustinoaq/vscode-crystal-lang/commit/cd116cecc31e17c717a6ee6c5c79eb417aa18dbc and https://github.com/kofno/scry/issues/3#issuecomment-312368919
