### ISSUE TITLE
"Array(Int32)" in argument highlighted incorrectly

### ISSUE THREAD

**Issue by Qwerp-Derp** [faustinoaq/vscode-crystal-lang#7]
```crystal
def next_step(cells : Array(Int32))
  new_cells = [] of Int32
  
  (0...cells.size).each do |index|
    current_cell = cells[index]
    next_cell = cells[(index + 1) % cells.size]

    current_cell = (current_cell + next_cell) % 3
    new_cells.push(current_cell)
  end

  return new_cells
end
```

The left bracket in `Array(Int32)` is highlighted incorrectly:

![screen shot 2017-07-29 at 3 11 07 pm](https://user-images.githubusercontent.com/14177193/28742348-78ef1f28-7470-11e7-8094-5cd0fa449ea1.png)

**Comment by faustinoaq** [comment]
Yes, is a crystal issue mainly, the same happens on other editors. Almost all syntax plugins are based on [this tmLanguage](https://github.com/crystal-lang/sublime-crystal/blob/master/Crystal.tmLanguage).

I did a [theme](https://marketplace.visualstudio.com/items?itemName=faustinoaq.theme-olivine-comments) as workaround for this issue:

![screenshot_20170729_042015](https://user-images.githubusercontent.com/3067335/28743666-3b544e78-7415-11e7-92bc-9b87af12aae7.png)

Maybe some syntax need to be fixed on [crystal.json](https://github.com/faustinoaq/vscode-crystal-lang/blob/master/syntaxes/crystal.json) currently based on Ruby syntax.

**Comment by faustinoaq** [comment]
Thanks you for find this issue, also I found that other parameters coloring is broken.

![screenshot_20170729_065000](https://user-images.githubusercontent.com/3067335/28744626-589d3cbe-742a-11e7-9bda-1fe815d043bd.png)

**Comment by faustinoaq** [comment]
@Qwerp-Derp I found the issue. The Crystal syntax `.tmLanguage` don't have any rules to parameters with types. As far I can I changed the `endCapture` to get all parameters using:

```
"end": "\\)\\s*$|\\)\\s*:",
```
